// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/git-hub": {
            "post": {
                "description": "Approve, merge, or approve and merge a GitHub pull request from the G97-TECH-MKT organization.\nIf no action is provided, defaults to \"both\" (approve + squash merge).\n\n**Allowed actions:**\n- ` + "`" + `approve` + "`" + ` — Approves the pull request\n- ` + "`" + `merge` + "`" + ` — Squash merges the pull request\n- ` + "`" + `both` + "`" + ` — Approves and then squash merges (default)\n\n**URL format:** ` + "`" + `https://github.com/G97-TECH-MKT/{repo}/pull/{number}` + "`" + `",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pull-requests"
                ],
                "summary": "Perform actions on a GitHub pull request",
                "parameters": [
                    {
                        "description": "Pull request action payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/GitHubRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Action completed successfully",
                        "schema": {
                            "$ref": "#/definitions/SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid URL, repository, or action",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "405": {
                        "description": "Method not allowed (only POST)",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to approve or merge the pull request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Invalid action"
                },
                "status": {
                    "type": "string",
                    "example": "error"
                }
            }
        },
        "GitHubRequest": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string",
                    "enum": [
                        "approve",
                        "merge",
                        "both"
                    ],
                    "example": "both"
                },
                "url": {
                    "type": "string",
                    "example": "https://github.com/G97-TECH-MKT/my-repo/pull/42"
                }
            }
        },
        "SuccessResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Pull request approved and merged"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "PR Approved API",
	Description:      "Service to approve and merge GitHub pull requests",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
